apiVersion: apps/v1
kind: Deployment
metadata:
  name: someapp
  labels:
    app: someapp
spec:
  selector:
    matchLabels:
      app: someapp
  template:
    metadata:
      labels:
        app: someapp
    spec:
      containers:
        - name: container-1
          securityContext:
            privileged: true
        - name: container-2
          securityContext:
            privileged: true
        - name: container-6
          securityContext:
            privileged: true
            allowPrivilegeEscalation: false

